Repository monsieurbiz/SyliusSearchPlugin, pull requests merged in 2022-08, with the labels that each got.

#134 Trim the query in request
  .github/workflows/tests.yaml
  src/Search/Request/ProductRequest/InstantSearch.php
  src/Search/Request/ProductRequest/Search.php
  src/Search/Request/RequestConfiguration.php
Labels: Status: needs review

#132 Add hash to output javascript filename
  webpack.config.js
Labels: quick win

#135 Became compatible with channel based index name
  src/EventSubscriber/AppendProductAttributeMappingSubscriber.php
  src/Search/Response/FilterBuilders/Product/AttributeFilterBuilder.php
  src/Search/Response/FilterBuilders/Product/MainTaxonFilterBuilder.php
  src/Search/Response/FilterBuilders/Product/OptionFilterBuilder.php
  src/Search/Response/FilterBuilders/Product/PriceFilterBuilder.php
  src/Search/Response/FilterBuilders/Product/TaxonsFilterBuilder.php
Labels: enhancement, Status: needs review
