Repository monsieurbiz/SyliusSearchPlugin, pull requests merged in 2023-10, with the labels that each got.

#191 typo parameter name add_custom_boosts.md
  docs/add_custom_boosts.md
Labels: quick win

#193 Correct title levels in custom entities doc
  docs/add_custom_entities.md
Labels: Status: needs review

#194 Add columns in options and attributes grid
  src/Form/Extension/ProductOptionTypeExtension.php
  src/Resources/config/config.yaml
  src/Resources/config/sylius/grids.yaml
  src/Resources/translations/messages.en.yml
  src/Resources/translations/messages.fr.yml
Labels: Status: needs review

#192 Add search weight in fixtures
  src/Fixture/Factory/SearchableFixtureFactory.php
  src/Fixture/SearchableFixture.php
  src/Resources/config/sylius/fixtures.yaml
Labels: Status: needs review

#196 Fields to search in parameters
  dist/src/Resources/config/config.yaml
  dist/src/Resources/config/services.yaml
  docs/add_custom_boosts.md
  docs/add_custom_entities.md
  docs/add_custom_sorts.md
  docs/add_custom_values.md
  src/Resources/config/services.yaml
Labels: Status: needs review

#197 doc: Add banner in README
  README.md
  docs/images/banner.jpg
Labels: documentation, quick win, Status: needs review
