Repository monsieurbiz/SyliusSearchPlugin, pull requests merged in 2023-08, with the labels that each got.

#177 Add config path in add entity doc
  docs/add_custom_entities.md
Labels: quick win, Status: needs review

#178 Use DTO ID to be able to have custom IDs
  src/Index/Indexer.php
Labels: quick win, Status: needs review

#176 Remove Trailing comma for php 7
  src/Search/Request/ProductRequest/Search.php
Labels: quick win, Status: needs review

#179 Append default analyzer if no locale
  src/Mapping/YamlWithLocaleProvider.php
Labels: quick win, Status: needs review

#184 Display index prefix on reindex console
  src/Index/Indexer.php
Labels: Status: needs review

#185 URL decode the query in the request configuration
  src/Search/Request/RequestConfiguration.php
Labels: quick win

#183 Update default mapping_provider class in comment
  dist/src/Resources/config/search/taxons.yaml
  src/Resources/config/monsieurbiz_search.yaml
Labels: quick win

#189 Add config with url in checker to avoid error couldn’t resolve host
  src/Checker/ElasticsearchChecker.php
  src/Resources/config/services.yaml
Labels: Status: needs review
