Repository monsieurbiz/SyliusSearchPlugin, pull requests merged in 2023-06, with the labels that each got.

#158 Correctly uses manifest.json to include JS with hash
  src/Resources/config/config.yaml
  src/Resources/public/entrypoints.json
  src/Resources/public/js/monsieurbiz-search.d29ecf2c.js
  src/Resources/public/js/monsieurbiz-search.js
  src/Resources/public/manifest.json
  src/Resources/views/_scripts.html.twig
  webpack.config.js
Labels: Status: needs review

#160 Sylius 1.12 and SF6 compatibility
  .github/workflows/recipe.yaml
  .github/workflows/security.yaml
  .github/workflows/tests.yaml
  .php-version.dist
  Makefile
  composer.json
  src/DependencyInjection/MonsieurBizSyliusSearchExtension.php
  src/Resources/config/routing/shop.yaml
  src/Resources/views/Search/_filters.html.twig
  src/Resources/views/Search/_pagination.html.twig
  src/Resources/views/Search/_sorting.html.twig
Labels: Status: needs review

#157 Correct default settings valus when many documentable entities
  src/DependencyInjection/DocumentableRegistryPass.php
Labels: quick win

#127 call getPrice only if channelPrice is not null
  src/Model/Documentable/DocumentableProductTrait.php
Labels: quick win, Status: needs review

#99 Use current attribute option value if it is not translatable
  src/Model/Documentable/DocumentableProductTrait.php
Labels: Status: needs review
